---
# Disable all repositories
- name: BASTION |configure_repos | Disable all repositories (RHN)
  command: subscription-manager repos --disable="*"

# Disable the AWS RHUI repositories
- name: BASTION |configure_repos | Remove RHUI repositories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/yum.repos.d/redhat-rhui-client-config.repo
    - /etc/yum.repos.d/redhat-rhui.repo
    - /etc/yum.repos.d/rhui-load-balancers.conf
  notify: yum-clean-all

- name: BASTION |configure_repos | Enable the correct repos for Ansible
  command: subscription-manager repos  --enable rhel-7-server-ose-{{ ocp_version }}-rpms --enable rhel-7-server-rpms --enable rhel-7-server-optional-rpms --enable rhel-7-server-extras-rpms
  when: deploy_ansible

- name: BASTION |configure_repos | Enable the Satellite Tools Repository when registered to Satellite server
  command: subscription-manager repos --enable rhel-7-server-satellite-tools-{{ satellite_version }}-rpms
  when: use_satellite

