---
- include: rhn_registration.yml
  when: rhn_registration

- include: sat_registration.yml
  when: use_satellite

- include: packaes_and_configurations.yml
- include: configure_repos.yml

- include: aws_cli.yml

- include: ssh_config.yml
- include: clone_repository.yml
  when: clone_repoistories
