---
- name: ANSIBLE | install_software | Install katello-agent if use_satellite == true
  yum:
    name: katello-agent
    state: present
  when: use_satellite

- name: ANSIBLE | install_software | Activate katello-agent "goferd" if use_satellite == true
  systemd:
    name: goferd
    state: started
    enabled: true
  when: use_satellite

- name: ANSIBLE | install_software | Install common package set
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ common_package_list }}"

- name: ANSIBLE | install_software | Install packages (Ansible)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ansible_package_list }}"
  when: ( use_satellite ) or ( rhn_registration )

- name: ANSIBLE | install_software | Install packages (Openshift)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ openshift_package_list }}"
  when: 
    - ( use_satellite ) or ( rhn_registration )
    - openshift_installer

