---
# Register an Ansible node to Satellite
- name: ANSIBLE | satellite registration | Install the Satellite SSL keys
  yum:
    name: '{{ sat_url }}'
    state: present

- name: ANSIBLE | satellite registration | Register an Ansible Node
  redhat_subscription:
    activationkey: '{{ sat_activation_key }}'
    org_id: '{{ sat_organization }}'
    autosubscribe: true
  when: deploy_ansible
