---
- name: | ANSIBLE | root ssh config | Create root's .ssh directory
  file:
    src: /root/.ssh
    owner: root
    group: root
    mode: 0700
    state: directory

- name: | ANSIBLE | root ssh config | Copy AWS private key file into root/.ssh
  copy:
    src: '{{ aws_private_key }}'
    dest: "/root/.ssh/{{ aws_private_key }}"
    owner: root
    group: root
    mode: 0600

- name: | ANSIBLE | root ssh config | Set up .ssh/config file
  tempalte: 
    src: ssh_config.j2
    dest: "/root/.ssh/config"
    owner: root
    group: root
    mode: 0600
  with_items: '{{ ssh_config_entries }}'

