---
- name: | BASTION | root ssh config | Create root's .ssh directory
  file:
    src: /root/.ssh
    owner: root
    group: root
    mode: 0700
    state: directory

- name: | BASTION | root ssh config | Copy AWS private key file into root/.ssh
  copy:
    src: files/'{{ aws_private_key }}'
    dest: /root/.ssh/'{{ aws_private_key }}'
    owner: root
    group: root
    mode: 0600

- name: | BASTION | root ssh config | Set up .ssh/config file
  blockinfile:
    block: |
      Host '{{ item }}'
        User '{{ aws_user }}'
        IdentityFile /root/.ssh/'{{ aws_privare_key}}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    dest: "/root/.ssh/config"
    owner: root
    group: root
    mode: 0600
  with_items: '{{ ssh_config_entries }}'
